# Generated by Django 3.2.1 on 2022-03-30 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture'),
            preserve_default=False,
        ),
    ]
