# Generated by Django 3.2.1 on 2022-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_api_app', '0002_lead_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture'),
        ),
    ]
